/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./components/ArticleCard/index.vue')['default']
    Footer: typeof import('./components/Footer/index.vue')['default']
    Header: typeof import('./components/Header/index.vue')['default']
    Layout: typeof import('./components/Layout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
