/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiSummary: typeof import('./components/AiSummary/index.vue')['default']
    ArticleCover: typeof import('./components/ArticleCover/index.vue')['default']
    Card: typeof import('./components/Card/index.vue')['default']
    Category: typeof import('./components/Category/index.vue')['default']
    CategoryItem: typeof import('./components/Category/components/CategoryItem/index.vue')['default']
    Comment: typeof import('./components/Comment/index.vue')['default']
    FancyBox: typeof import('./components/FancyBox/index.vue')['default']
    Footer: typeof import('./components/Footer/index.vue')['default']
    Header: typeof import('./components/Header/index.vue')['default']
    Introduce: typeof import('./components/Introduce/index.vue')['default']
    Layout: typeof import('./components/Layout/index.vue')['default']
    List: typeof import('./components/List/index.vue')['default']
    ListItem: typeof import('./components/List/components/ListItem/index.vue')['default']
    Music: typeof import('./components/Music/index.vue')['default']
    Nav: typeof import('./components/Nav/index.vue')['default']
    Pagination: typeof import('./components/Pagination/index.vue')['default']
    Pop: typeof import('./components/Pop/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search/index.vue')['default']
    SpliceLine: typeof import('./components/SpliceLine/index.vue')['default']
    StatisticCard: typeof import('./components/StatisticCard/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    TimeLine: typeof import('./components/TimeLine/index.vue')['default']
    TodoList: typeof import('./components/TodoList/index.vue')['default']
    Tools: typeof import('./components/Tools/index.vue')['default']
    Typed: typeof import('./components/AiSummary/components/Typed/index.vue')['default']
    Weather: typeof import('./components/Weather/index.vue')['default']
  }
}
